@baseUrl = http://localhost:8080/api/v1
@phone = +2347015332038
@emergencyContactPhone = +2348012345678


### Get My Profile
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}
Accept: application/json


