-- Seeds a common-allergens starter catalog. Category integers match
-- internal/domain/valueobjects/allergy.go: 1=Food, 2=Drug,
-- 3=Environmental, 4=Contact, 5=Other.
INSERT INTO allergies (name, category, description) VALUES
    ('Peanuts', 1, 'One of the most common and severe food allergies.'),
    ('Tree nuts', 1, 'Includes almonds, walnuts, cashews, and pistachios.'),
    ('Shellfish', 1, 'Includes shrimp, crab, and lobster.'),
    ('Fish', 1, 'Includes finned fish such as salmon and tuna.'),
    ('Milk', 1, 'Allergy to milk proteins, distinct from lactose intolerance.'),
    ('Eggs', 1, 'Common in children, often outgrown.'),
    ('Wheat', 1, 'Distinct from celiac disease and gluten sensitivity.'),
    ('Soy', 1, 'Common in infants and young children.'),
    ('Sesame', 1, 'Increasingly recognized as a major food allergen.'),
    ('Penicillin', 2, 'One of the most commonly reported drug allergies.'),
    ('Sulfa drugs', 2, 'Includes sulfonamide antibiotics.'),
    ('Aspirin', 2, 'Can trigger reactions in sensitive individuals.'),
    ('NSAIDs', 2, 'Includes ibuprofen and naproxen.'),
    ('Local anesthetics', 2, 'Reactions to agents used in dental or minor procedures.'),
    ('Contrast dye', 2, 'Used in imaging procedures such as CT scans.'),
    ('Pollen', 3, 'Seasonal allergen from trees, grasses, and weeds.'),
    ('Dust mites', 3, 'A leading cause of year-round allergy symptoms.'),
    ('Mold', 3, 'Found indoors and outdoors, especially in damp areas.'),
    ('Pet dander', 3, 'Common trigger from cats, dogs, and other animals.'),
    ('Insect stings', 3, 'Includes bee, wasp, and hornet stings.'),
    ('Latex', 4, 'Common in healthcare settings due to glove and equipment use.'),
    ('Nickel', 4, 'A frequent cause of contact dermatitis from jewelry and metal.'),
    ('Fragrances', 4, 'Found in perfumes, cosmetics, and cleaning products.'),
    ('Poison ivy', 4, 'Causes contact dermatitis from plant oils.'),
    ('Other', 5, 'Allergy not covered by the categories above.');
