[global]
    update every = 5

[db]
    mode = dbengine
    storage tiers = 1
    dbengine page cache size = 32MiB
    dbengine extent cache size = 8MiB
    dbengine tier 0 disk space MB = 256
    dbengine tier 0 retention days = 3

[ml]
    enabled = no
